# ==============================================================================
# Get-PostReviewMembershipDelta.ps1
# Scenario 11 - Entra Access Reviews
# IDSentinel Solutions | Cleveland Oliver
#
# Purpose:
#   Compares the pre-review baseline CSV against current group membership
#   to produce a before/after membership delta report. Documents exactly
#   which members were removed as a result of the completed access review.
#
# Usage:
#   .\Get-PostReviewMembershipDelta.ps1 -BaselineCsvPath "..\audit-exports\privileged-group-baseline_2026-05-18_1533.csv"
#
# Requirements:
#   - Microsoft.Graph PowerShell module
#   - Group.Read.All, User.Read.All permissions
#   - Baseline CSV generated by Get-PrivilegedGroupBaseline.ps1
# ==============================================================================

param(
    [Parameter(Mandatory = $true)]
    [string]$BaselineCsvPath
)

# -- Config --------------------------------------------------------------------
$GroupDisplayName = "GRP-SEC-PrivilegedUsers"
$OutputDir        = "$PSScriptRoot\..\audit-exports"
$Timestamp        = Get-Date -Format "yyyy-MM-dd_HHmm"
$DeltaFile        = "$OutputDir\membership-delta_$Timestamp.csv"

# -- Validate Baseline File ----------------------------------------------------
if (-not (Test-Path $BaselineCsvPath)) {
    Write-Host "[!] Baseline CSV not found: $BaselineCsvPath" -ForegroundColor Red
    exit 1
}

$Baseline = Import-Csv -Path $BaselineCsvPath
Write-Host "[+] Loaded baseline: $($Baseline.Count) members from $BaselineCsvPath" -ForegroundColor Green

# -- Connect -------------------------------------------------------------------
Write-Host "[*] Connecting to Microsoft Graph..." -ForegroundColor Cyan
Connect-MgGraph -Scopes "Group.Read.All","User.Read.All","Directory.Read.All" -NoWelcome

# -- Get Current Group Membership ----------------------------------------------
Write-Host "[*] Resolving group: $GroupDisplayName" -ForegroundColor Cyan
$Group = Get-MgGroup -Filter "displayName eq '$GroupDisplayName'" -Property "Id,DisplayName"

if (-not $Group) {
    Write-Host "[!] Group '$GroupDisplayName' not found." -ForegroundColor Red
    exit 1
}

$CurrentMembers = Get-MgGroupMemberAsUser -GroupId $Group.Id -All `
    -Property "Id,DisplayName,UserPrincipalName,Department,JobTitle"

Write-Host "[+] Current member count: $($CurrentMembers.Count)" -ForegroundColor Green

# -- Compute Delta -------------------------------------------------------------
$BaselineUPNs = $Baseline | Select-Object -ExpandProperty UserPrincipalName
$CurrentUPNs  = $CurrentMembers | Select-Object -ExpandProperty UserPrincipalName

$Removed  = $Baseline | Where-Object { $_.UserPrincipalName -notin $CurrentUPNs }
$Added    = $CurrentMembers | Where-Object { $_.UserPrincipalName -notin $BaselineUPNs }
$Retained = $CurrentMembers | Where-Object { $_.UserPrincipalName -in $BaselineUPNs }

# -- Build Delta Report --------------------------------------------------------
$DeltaReport = @()

foreach ($User in $Retained) {
    $DeltaReport += [PSCustomObject]@{
        DisplayName       = $User.DisplayName
        UserPrincipalName = $User.UserPrincipalName
        Department        = $User.Department
        Status            = "RETAINED"
        ChangeReason      = "Access approved in review"
        ReportDate        = (Get-Date -Format "yyyy-MM-dd HH:mm")
    }
}

foreach ($User in $Removed) {
    $DeltaReport += [PSCustomObject]@{
        DisplayName       = $User.DisplayName
        UserPrincipalName = $User.UserPrincipalName
        Department        = $User.Department
        Status            = "REMOVED"
        ChangeReason      = "Access denied - removed by Access Review policy"
        ReportDate        = (Get-Date -Format "yyyy-MM-dd HH:mm")
    }
}

foreach ($User in $Added) {
    $DeltaReport += [PSCustomObject]@{
        DisplayName       = $User.DisplayName
        UserPrincipalName = $User.UserPrincipalName
        Department        = $User.Department
        Status            = "ADDED"
        ChangeReason      = "Added outside of review cycle - investigate if unexpected"
        ReportDate        = (Get-Date -Format "yyyy-MM-dd HH:mm")
    }
}

# -- Display Results -----------------------------------------------------------
Write-Host "`n-- Membership Delta Report ------------------------------------------" -ForegroundColor Cyan

if ($Removed.Count -gt 0) {
    Write-Host "`n  REMOVED ($($Removed.Count)) - Access review enforcement:" -ForegroundColor Red
    $Removed | Format-Table DisplayName, UserPrincipalName, Department -AutoSize
} else {
    Write-Host "  REMOVED: None" -ForegroundColor Gray
}

if ($Added.Count -gt 0) {
    Write-Host "  ADDED ($($Added.Count)) - Added outside review cycle:" -ForegroundColor Yellow
    $Added | Format-Table DisplayName, UserPrincipalName, Department -AutoSize
    Write-Host "  [!] Review unexpected additions for unauthorized provisioning." -ForegroundColor Yellow
} else {
    Write-Host "  ADDED: None" -ForegroundColor Gray
}

Write-Host "`n-- Summary ----------------------------------------------------------" -ForegroundColor Cyan
Write-Host "  Baseline members : $($Baseline.Count)"
Write-Host "  Current members  : $($CurrentMembers.Count)"
Write-Host "  Retained         : $($Retained.Count)" -ForegroundColor Green
Write-Host "  Removed          : $($Removed.Count)"  -ForegroundColor Red
Write-Host "  Added (anomaly)  : $($Added.Count)"    -ForegroundColor Yellow

# -- Export --------------------------------------------------------------------
if (-not (Test-Path $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir | Out-Null }
$DeltaReport | Export-Csv -Path $DeltaFile -NoTypeInformation -Encoding UTF8

Write-Host "`n[+] Delta report exported: $DeltaFile" -ForegroundColor Green
Write-Host "[i] Pair this with the audit trail export for a complete SOC 2 evidence package." -ForegroundColor DarkCyan
Write-Host ""